name = "${D1_PHOTO_ALBUMS_WORKER}"
main = "src/worker.ts"
compatibility_date = "2025-10-20"
compatibility_flags = ["nodejs_compat"]

# Default (dev) binding
[[d1_databases]]
binding = "DB"
database_name = "${DEV_PHOTO_ALBUMS_DB_NAME}"
database_id = "${DEV_PHOTO_ALBUMS_DB_ID}"

[vars]
AWS_S3_BUCKET_NAME = "${AWS_S3_BUCKET_NAME}"
AWS_REGION_NAME = "${AWS_REGION_NAME}"
VITE_IMAGEKIT_CDN_URL = "${VITE_IMAGEKIT_CDN_URL}"
VITE_GOOGLE_CLIENT_ID = "${VITE_GOOGLE_CLIENT_ID}"
ALBUM_URL = "${ALBUM_URL}"
AWS_ACCESS_KEY_ID = "${AWS_ACCESS_KEY_ID}"
AWS_SECRET_ACCESS_KEY = "${AWS_SECRET_ACCESS_KEY}"
GOOGLE_PLACES_API_KEY = "${GOOGLE_PLACES_API_KEY}"
JWT_SECRET = "${JWT_SECRET}"

# Production binding
[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "${PROD_PHOTO_ALBUMS_DB_NAME}"
database_id = "${PROD_PHOTO_ALBUMS_DB_ID}"

[env.production.vars]
AWS_S3_BUCKET_NAME = "${AWS_S3_BUCKET_NAME}"
AWS_REGION_NAME = "${AWS_REGION_NAME}"
VITE_IMAGEKIT_CDN_URL = "${VITE_IMAGEKIT_CDN_URL}"
VITE_GOOGLE_CLIENT_ID = "${VITE_GOOGLE_CLIENT_ID}"
ALBUM_URL = "${ALBUM_URL}"
AWS_ACCESS_KEY_ID = "${AWS_ACCESS_KEY_ID}"
AWS_SECRET_ACCESS_KEY = "${AWS_SECRET_ACCESS_KEY}"
GOOGLE_PLACES_API_KEY = "${GOOGLE_PLACES_API_KEY}"
JWT_SECRET = "${JWT_SECRET}"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
head_sampling_rate = 1
persist = true