name = "${D1_PHOTO_ALBUMS_WORKER}"
main = "src/worker.ts"
compatibility_date = "2025-10-20"
compatibility_flags = ["nodejs_compat"]

# Default (dev) binding
[[d1_databases]]
binding = "DB"
database_name = "${DEV_PHOTO_ALBUMS_DB_NAME}"
database_id = "${DEV_PHOTO_ALBUMS_DB_ID}"

[vars]
WORKER_SECRET = "${WORKER_SECRET}"


# Production binding
[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "${PROD_PHOTO_ALBUMS_DB_NAME}"
database_id = "${PROD_PHOTO_ALBUMS_DB_ID}"

[env.production.vars]
WORKER_SECRET = "${WORKER_SECRET}"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
head_sampling_rate = 1
persist = true