name = "${D1_PHOTO_ALBUMS_WORKER}"
main = "src/d1/worker.ts"
compatibility_date = "2025-10-20"
compatibility_flags = ["nodejs_compat"]

# Default (dev) binding
[[d1_databases]]
binding = "DB"
database_name = "${DEV_PHOTO_ALBUMS_DB_NAME}"
database_id = "${DEV_PHOTO_ALBUMS_DB_ID}"

[vars]
WORKER_SECRET = "${DEV_WORKER_SECRET}"


# Production binding
[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "${PROD_PHOTO_ALBUMS_DB_NAME}"
database_id = "${PROD_PHOTO_ALBUMS_DB_ID}"

[env.production.vars]
WORKER_SECRET = "${PROD_WORKER_SECRET}"